# Feature extraction

In this notebook we will learn how to extract different features from a text and how to combine them. It's pretty simple, but if you have this part well organized, it will be really useful in the near future. So, let's get started!

In [296]:
import nltk
from sklearn.pipeline import FeatureUnion
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn import preprocessing
from scipy.sparse import coo_matrix, hstack

In [193]:
from sklearn.preprocessing import LabelEncoder
import os
import glob
import json
import argparse
import time
import codecs
from collections import defaultdict
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import preprocessing
from sklearn.calibration import CalibratedClassifierCV

import nltk
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer

In [194]:
import re
import random
from sklearn.pipeline import Pipeline

In [195]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /Users/sallyisa/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/sallyisa/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [196]:
import os

In [267]:
from nltk.tokenize import word_tokenize

def get_pos(text):
    pos_tags= nltk.pos_tag(word_tokenize(text))
    # print(len(pos_tags))
    pos_tags = [word_tag[1] for word_tag in pos_tags]
    pos_text = ' '.join(pos_tags)
    return pos_tags

get_pos(train_sents[0])

['JJ',
 'NNS',
 '.',
 '``',
 'CD',
 'JJR',
 ',',
 "''",
 'NNP',
 'VBD',
 ',',
 'VBG',
 'RB',
 'VBN',
 'IN',
 'PRP$',
 'NN',
 '.',
 '``',
 'PRP',
 'VBD',
 'RB',
 'VBN',
 ',',
 "''",
 'NNP',
 'VBD',
 ',',
 'IN',
 'RB',
 'RB',
 '.',
 '(',
 'DT',
 'NN',
 'NN',
 ')',
 '.',
 'PRP',
 'VBD',
 'RB',
 ':',
 'PRP$',
 'NNS',
 'VBP',
 'RB',
 'IN',
 'VBN',
 'TO',
 'NN',
 'IN',
 'NN',
 'CC',
 'PRP$',
 'NNS',
 'VBD',
 'TO',
 'VB',
 'PRP$',
 'JJ',
 '.',
 'CC',
 'VBD',
 'IN',
 'PRP',
 'VBD',
 'VBG',
 'TO',
 'VB',
 'NNP',
 'NNP',
 'NN',
 'VBD',
 'NN',
 'TO',
 'VB',
 'PRP$',
 'NN',
 ',',
 'CC',
 'VBD',
 'IN',
 'PRP',
 'VBD',
 'VBG',
 'TO',
 'VB',
 'PRP',
 'VB',
 'IN',
 'DT',
 'NN',
 'IN',
 'NN',
 'IN',
 'NNP',
 ',',
 'WP',
 ':',
 'IN',
 'PRP',
 'VBD',
 'PRP',
 'CC',
 'RB',
 ':',
 'VBD',
 'DT',
 'NN',
 'NN',
 '.',
 'NNP',
 'VBD',
 'VBN',
 'TO',
 'VB',
 'PRP$',
 'NN',
 'TO',
 'DT',
 'IN',
 'PRP',
 ',',
 'DT',
 'NN',
 'WP',
 'PRP',
 'VBD',
 '.',
 'IN',
 'PRP',
 'VBD',
 'NNP',
 'NNP',
 'JJ',
 'NN',
 'RB',
 'C

In [268]:
def get_pos_ngrams(sents):
    pos_tags= [nltk.pos_tag(word_tokenize(sents[ind])) for ind, item in enumerate(sents) if item != '']
    pos_sents = []
    for sent in pos_tags:
        #print(sent)
        pos = ' '.join([pos_tag[1] for pos_tag in sent])
        #print(pos, '\n')
        pos_sents.append(pos)
    vectorizer = CountVectorizer(ngram_range = (1,1))
    vectorizer.fit(pos_sents)
    return vectorizer


pos_vectorizer = get_pos_ngrams(train_sents)
pos_ngram = pos_vectorizer.transform(train_sents)
pos_ngram

<7x31 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [269]:
# -*- coding: utf-8 -*-

"""
 A baseline authorship attribution method 
 based on a character n-gram representation
 and a linear SVM classifier.
 It has a reject option to leave documents unattributed
 (when the probabilities of the two most likely training classes are too close)
 
 Questions/comments: stamatatos@aegean.gr

 It can be applied to datasets of PAN-19 cross-domain authorship attribution task
 See details here: http://pan.webis.de/clef19/pan19-web/author-identification.html
 Dependencies:
 - Python 2.7 or 3.6 (we recommend the Anaconda Python distribution)
 - scikit-learn

 Usage from command line: 
    > python pan19-cdaa-baseline.py -i EVALUATION-DIRECTORY -o OUTPUT-DIRECTORY [-n N-GRAM-ORDER] [-ft FREQUENCY-THRESHOLD] [-pt PROBABILITY-THRESHOLD]
 EVALUATION-DIRECTORY (str) is the main folder of a PAN-19 collection of attribution problems
 OUTPUT-DIRECTORY (str) is an existing folder where the predictions are saved in the PAN-19 format
 Optional parameters of the model:
   N-GRAM-ORDER (int) is the length of character n-grams (default=3)
   FREQUENCY-THRESHOLD (int) is the cutoff threshold used to filter out rare n-grams (default=5)
   PROBABILITY-THRESHOLD (float) is the threshold for the reject option assigning test documents to the <UNK> class (default=0.1)
                                 Let P1 and P2 be the two maximum probabilities of training classes for a test document. If P1-P2<pt then the test document is assigned to the <UNK> class.
   
 Example:

     >  python pan19-cdaa-baseline-svm.py -i ".\pan19-cross-domain-authorship-attribution-training-dataset-2019-01-23\" -o ".\a
nswers-trigram\" -n 3
"""

from __future__ import print_function
import os
import glob
import json
import argparse
import time
import codecs
from collections import defaultdict
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import preprocessing
from sklearn.calibration import CalibratedClassifierCV

def represent_text(text,n,pos=False):
    # Extracts all character n-grams from  a 'text'
    # if pos is True, extracts POS n-grams
    if n>0:
        if pos is True:
            text = get_pos(text)
            tokens = [' '.join(text[i:i+n]) for i in range(len(text)-n+1)]
            #print(tokens)
        else:
            tokens = [text[i:i+n] for i in range(len(text)-n+1)]
    frequency = defaultdict(int)
    for token in tokens:
        frequency[token] += 1
    return frequency

represent_text(train_sents[0], 2)
represent_text(train_sents[0], 2, pos=True)
                           

defaultdict(int,
            {'JJ NNS': 2,
             'NNS .': 5,
             '. ``': 8,
             '`` CD': 2,
             'CD JJR': 2,
             'JJR ,': 2,
             ", ''": 6,
             "'' NNP": 7,
             'NNP VBD': 18,
             'VBD ,': 12,
             ', VBG': 5,
             'VBG RB': 3,
             'RB VBN': 5,
             'VBN IN': 2,
             'IN PRP$': 15,
             'PRP$ NN': 24,
             'NN .': 15,
             '`` PRP': 4,
             'PRP VBD': 37,
             'VBD RB': 10,
             'VBN ,': 1,
             ', IN': 4,
             'IN RB': 2,
             'RB RB': 5,
             'RB .': 7,
             '. (': 4,
             '( DT': 2,
             'DT NN': 35,
             'NN NN': 12,
             'NN )': 2,
             ') .': 1,
             '. PRP': 5,
             'RB :': 2,
             ': PRP$': 1,
             'PRP$ NNS': 11,
             'NNS VBP': 4,
             'VBP RB': 1,
             'RB IN': 4,
            

In [270]:
def read_files(path,label):
    # Reads all text files located in the 'path' and assigns them to 'label' class
    files = glob.glob(path+os.sep+label+os.sep+'*.txt')
    texts=[]
    for i,v in enumerate(files):
        f=codecs.open(v,'r',encoding='utf-8')
        texts.append((f.read(),label))
        f.close()
    return texts

def extract_vocabulary(texts,n,ft,pos=False):
    # Extracts all characer 'n'-grams occurring at least 'ft' times in a set of 'texts'
    occurrences=defaultdict(int) 
    for (text,label) in texts:
        text_occurrences = {}
        if isinstance(n, int):
            for x in range(1,n+1):
                text_occurrences.update(represent_text(text,x,pos=pos))
        else:
            pass
        for ngram in text_occurrences:
            if ngram in occurrences:
                occurrences[ngram]+=text_occurrences[ngram]
            else:
                occurrences[ngram]=text_occurrences[ngram]
    vocabulary=[]
    for i in occurrences.keys():
        if occurrences[i]>=ft:
            vocabulary.append(i)
    return vocabulary

vocab = extract_vocabulary([(x,i) for i, x in enumerate(train_sents)], 2, 5, pos=True)
print(len(vocab))
print(vocab)
vectorizer = CountVectorizer(vocabulary=[x.lower() for  x in vocab])
print([' '.join(get_pos(text)) for text in train_sents])

train_data = vectorizer.fit_transform([' '.join(get_pos(text)) for text in train_sents])
print(vectorizer.get_feature_names())
train_data = train_data.astype(float)
print(train_data.shape)
print(train_data.toarray())

287
['JJ', 'NNS', '.', '``', 'CD', 'JJR', ',', "''", 'NNP', 'VBD', 'VBG', 'RB', 'VBN', 'IN', 'PRP$', 'NN', 'PRP', '(', 'DT', ')', ':', 'VBP', 'TO', 'CC', 'VB', 'WP', 'RP', 'WRB', 'EX', 'VBZ', 'JJS', 'MD', 'PDT', 'WDT', 'JJ NNS', 'NNS .', '. ``', ", ''", "'' NNP", 'NNP VBD', 'VBD ,', ', VBG', 'VBG RB', 'RB VBN', 'VBN IN', 'IN PRP$', 'PRP$ NN', 'NN .', '`` PRP', 'PRP VBD', 'VBD RB', 'VBN ,', ', IN', 'IN RB', 'RB RB', 'RB .', '. (', 'DT NN', 'NN NN', '. PRP', 'RB :', 'PRP$ NNS', 'NNS VBP', 'VBP RB', 'RB IN', 'VBN TO', 'NN IN', 'IN NN', 'NN CC', 'CC PRP$', 'NNS VBD', 'VBD TO', 'TO VB', 'VB PRP$', 'PRP$ JJ', 'JJ .', '. CC', 'CC VBD', 'VBD IN', 'IN PRP', 'VBD VBG', 'VBG TO', 'VB NNP', 'NNP NNP', 'NNP NN', 'NN VBD', 'VBD NN', 'NN TO', 'NN ,', ', CC', 'VB PRP', 'PRP VB', 'VB IN', 'IN DT', 'IN NNP', 'NNP ,', ': IN', 'VBD PRP', 'PRP CC', 'CC RB', 'VBD DT', '. NNP', 'VBD VBN', 'TO DT', 'DT IN', 'PRP ,', ', DT', 'NN WP', 'WP PRP', 'VBD .', '. IN', 'VBD NNP', 'JJ NN', 'NN RB', 'RB CC', 'PRP RP', ',

['jj', 'nns', '.', '``', 'cd', 'jjr', ',', "''", 'nnp', 'vbd', 'vbg', 'rb', 'vbn', 'in', 'prp$', 'nn', 'prp', '(', 'dt', ')', ':', 'vbp', 'to', 'cc', 'vb', 'wp', 'rp', 'wrb', 'ex', 'vbz', 'jjs', 'md', 'pdt', 'wdt', 'jj nns', 'nns .', '. ``', ", ''", "'' nnp", 'nnp vbd', 'vbd ,', ', vbg', 'vbg rb', 'rb vbn', 'vbn in', 'in prp$', 'prp$ nn', 'nn .', '`` prp', 'prp vbd', 'vbd rb', 'vbn ,', ', in', 'in rb', 'rb rb', 'rb .', '. (', 'dt nn', 'nn nn', '. prp', 'rb :', 'prp$ nns', 'nns vbp', 'vbp rb', 'rb in', 'vbn to', 'nn in', 'in nn', 'nn cc', 'cc prp$', 'nns vbd', 'vbd to', 'to vb', 'vb prp$', 'prp$ jj', 'jj .', '. cc', 'cc vbd', 'vbd in', 'in prp', 'vbd vbg', 'vbg to', 'vb nnp', 'nnp nnp', 'nnp nn', 'nn vbd', 'vbd nn', 'nn to', 'nn ,', ', cc', 'vb prp', 'prp vb', 'vb in', 'in dt', 'in nnp', 'nnp ,', ': in', 'vbd prp', 'prp cc', 'cc rb', 'vbd dt', '. nnp', 'vbd vbn', 'to dt', 'dt in', 'prp ,', ', dt', 'nn wp', 'wp prp', 'vbd .', '. in', 'vbd nnp', 'jj nn', 'nn rb', 'rb cc', 'prp rp', ', jj'

In [300]:
def baseline(path,outpath,n=3,ft=5,pt=0.1):
    start_time = time.time()
    # Reading information about the collection
    infocollection = path+os.sep+'collection-info.json'
    problems = []
    language = []
    with open(infocollection, 'r') as f:
        for attrib in json.load(f):
            problems.append(attrib['problem-name'])
            language.append(attrib['language'])
    for index,problem in enumerate(problems):
        print(problem)
        # Reading information about the problem
        infoproblem = path+os.sep+problem+os.sep+'problem-info.json'
        candidates = []
        with open(infoproblem, 'r') as f:
            fj = json.load(f)
            unk_folder = fj['unknown-folder']
            for attrib in fj['candidate-authors']:
                candidates.append(attrib['author-name'])
        # Building training set
        train_docs=[]
        for candidate in candidates:
            train_docs.extend(read_files(path+os.sep+problem,candidate))
        train_texts = [text for i,(text,label) in enumerate(train_docs)]
        train_labels = [label for i,(text,label) in enumerate(train_docs)]
        #### Feature Extraction ###
        ###### Training Set #######
        ## Char-level n-grams ##
        char_vocab = extract_vocabulary(train_docs,n,ft)
        char_vectorizer = CountVectorizer(analyzer='char',ngram_range=(n,n),lowercase=False,vocabulary=char_vocab)
        char_train_data = char_vectorizer.fit_transform(train_texts)
        char_train_data = char_train_data.astype(float)
        print(char_train_data.shape)
        print(char_train_data.toarray())
        
        ## POS n-grams ##
        pos_vocab = [x.lower() for x in extract_vocabulary(train_docs,2,ft,pos=True)]
        print(pos_vocab)
        pos_vectorizer = CountVectorizer(ngram_range=(1,2), vocabulary=pos_vocab)
        pos_train_docs = [' '.join(get_pos(text)) for text in train_texts]
        print(pos_train_docs[0])
        train_data = pos_vectorizer.fit_transform(pos_train_docs)
        train_data = train_data.astype(float)
        print(train_data.shape)
        print(train_data.toarray()[:,1])
        print(train_data.shape, char_train_data.shape)
        train_data = hstack((train_data, char_train_data)) # put feature sets together
        print(train_data.shape)
        #for i,v in enumerate(train_texts):
            #print(i,v, train_data[i])
            #train_data[i]=train_data[i]/len(train_texts[i]) # normalizes over length of each text?
        print('\t', 'language: ', language[index])
        print('\t', len(candidates), 'candidate authors')
        print('\t', len(train_texts), 'known texts')
        print('\t', 'vocabulary size:', len(pos_vocab))
        
        ###### Test Set #######
        test_docs=read_files(path+os.sep+problem,unk_folder)
        test_texts = [text for i,(text,label) in enumerate(test_docs)]
        char_test_data = char_vectorizer.transform(test_texts)
        test_texts = [' '.join(get_pos(text)) for text in test_texts]
        test_data = pos_vectorizer.transform(test_texts)
        test_data = test_data.astype(float)
        
        test_data = hstack((test_data, char_test_data)) # put feature sets together
        #for i,v in enumerate(test_texts):
        #    test_data[i]=test_data[i]/len(test_texts[i])
        print('\t', len(test_texts), 'unknown texts')
        
        ###### Applying Classifiers #####
        max_abs_scaler = preprocessing.MaxAbsScaler()
        scaled_train_data = max_abs_scaler.fit_transform(train_data)
        scaled_test_data = max_abs_scaler.transform(test_data)
        clf=CalibratedClassifierCV(OneVsRestClassifier(SVC(C=1)))
        clf.fit(scaled_train_data, train_labels)
        predictions=clf.predict(scaled_test_data)
        proba=clf.predict_proba(scaled_test_data)
        # Reject option (used in open-set cases)
        count=0
        for i,p in enumerate(predictions):
            sproba=sorted(proba[i],reverse=True)
            if sproba[0]-sproba[1]<pt:
                predictions[i]=u'<UNK>'
                count=count+1
        print('\t',count,'texts left unattributed')
        # Saving output data
        out_data=[]
        unk_filelist = glob.glob(path+os.sep+problem+os.sep+unk_folder+os.sep+'*.txt')
        pathlen=len(path+os.sep+problem+os.sep+unk_folder+os.sep)
        for i,v in enumerate(predictions):
            out_data.append({'unknown-text': unk_filelist[i][pathlen:], 'predicted-author': v})
        with open(outpath+os.sep+'answers-'+problem+'.json', 'w') as f:
            json.dump(out_data, f, indent=4)
        print('\t', 'answers saved to file','answers-'+problem+'.json')
    print('elapsed time:', time.time() - start_time)

base_dir='pan18-cross-domain-authorship-attribution-training-dataset-2017-12-02'
out_dir = base_dir+os.sep+'output-dir'
eval_dir = base_dir+os.sep+'eval-dir'
baseline(base_dir,out_dir,n=5,ft=3,pt=0.05)
%timeit

problem00001
(140, 64239)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 3. 3. 4.]]
['jj', 'nns', '.', '``', 'cd', 'jjr', ',', "''", 'nnp', 'vbd', 'vbg', 'rb', 'vbn', 'in', 'prp$', 'nn', 'prp', '(', 'dt', ')', ':', 'vbp', 'to', 'cc', 'vb', 'wp', 'rp', 'wrb', 'ex', 'vbz', 'jjs', 'md', 'pdt', 'uh', 'wdt', 'jj nns', 'nns .', '. ``', '`` cd', 'cd jjr', 'jjr ,', ", ''", "'' nnp", 'nnp vbd', 'vbd ,', ', vbg', 'vbg rb', 'rb vbn', 'vbn in', 'in prp$', 'prp$ nn', 'nn .', '`` prp', 'prp vbd', 'vbd rb', 'vbn ,', ', in', 'in rb', 'rb rb', 'rb .', '. (', '( dt', 'dt nn', 'nn nn', 'nn )', ') .', '. prp', 'rb :', ': prp$', 'prp$ nns', 'nns vbp', 'vbp rb', 'rb in', 'in vbn', 'vbn to', 'to nn', 'nn in', 'in nn', 'nn cc', 'cc prp$', 'nns vbd', 'vbd to', 'to vb', 'vb prp$', 'prp$ jj', 'jj .', '. cc', 'cc vbd', 'vbd in', 'in prp', 'vbd vbg', 'vbg to', 'vb nnp', 'nnp nnp', 'nnp nn', 'nn vbd', 'vbd nn', 'nn to'

JJ NNS . `` CD JJR , '' NNP VBD , VBG RB VBN IN PRP$ NN . `` PRP VBD RB VBN , '' NNP VBD , IN RB RB . ( DT NN NN ) . PRP VBD RB : PRP$ NNS VBP RB IN VBN TO NN IN NN CC PRP$ NNS VBD TO VB PRP$ JJ . CC VBD IN PRP VBD VBG TO VB NNP NNP NN VBD NN TO VB PRP$ NN , CC VBD IN PRP VBD VBG TO VB PRP VB IN DT NN IN NN IN NNP , WP : IN PRP VBD PRP CC RB : VBD DT NN NN . NNP VBD VBN TO VB PRP$ NN TO DT IN PRP , DT NN WP PRP VBD . IN PRP VBD NNP NNP JJ NN RB CC VBD PRP RP DT NN NN , CC VBD DT NN IN PRP$ NN , JJ PRP$ NN RB TO VB PRP . `` CD JJR , '' PRP VBD , NN NN , CC NNP VBD IN DT NN . JJ VBN . ( VBG NNS , DT IN PRP . ) : DT JJ NNS IN PRP$ NN , CC NNP VBD NNP VBD RB RB JJ IN VBG PRP$ NN . `` PRP VBP TO VB WRB TO VB PRP$ JJ JJ NN NNS CC VBP PRP$ JJ NN , '' NNP VBD , CC EX VBD DT JJ NN IN PRP$ NN RB . ( RB PRP VBZ NN IN PRP VBD JJ NN NN , IN NNP VBD PRP VBD NNP JJ NN IN PRP VBD RB VBN NNP IN JJS RB , CC NNP VBD RB DT NN TO VB PRP TO VB RB IN PRP MD VBG NN CC VBD JJ IN PRP . ) PRP VBD PRP NNS IN PRP 

/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:19

	 31 texts left unattributed
	 answers saved to file answers-problem00001.json
problem00002
(35, 26761)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 3. 3. 3.]]
['dt', 'nn', '.', "''", 'nnp', 'rb', 'vbz', 'in', ',', 'jj', '``', 'prp', 'md', 'vb', 'to', 'vbg', 'rp', 'prp$', 'vbd', 'wp', 'nns', 'vbp', 'cc', 'vbn', 'cd', ':', 'pos', 'wrb', 'jjs', 'uh', 'rbs', 'pdt', 'dt nn', 'nn .', ". ''", "'' nnp", 'nnp rb', 'rb vbz', 'vbz dt', '. in', 'in nnp', 'nnp ,', ', dt', 'nn in', 'in dt', 'dt vbz', 'vbz jj', 'jj .', '. ``', '`` in', 'in prp', 'prp md', 'md rb', 'rb vb', 'vb to', 'to prp', 'prp .', '. rb', 'rb ,', ", ''", 'nnp vbz', 'vbz ,', ', vbg', 'vbg rp', 'rp prp$', 'prp$ nn', 'nn ,', 'dt jj', 'jj nn', 'in nn', '. nnp', 'nnp vbd', 'vbd prp', 'prp rb', 'rb .', '`` wp', 'wp vbz', 'vbz prp', 'vbz prp$', 'prp$ nns', 'nns rb', 'vbg .', '`` prp', 'prp vbz', ', nn', '. wp', 'prp vb', 'vb in', 'in .', 

	 21 unknown texts


/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/sallyisa/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:19

	 6 texts left unattributed
	 answers saved to file answers-problem00002.json
elapsed time: 53.47732400894165


In [301]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
# Evaluation script for the Cross-Domain Authorship Attribution task @PAN2019.
We use the F1 metric (macro-average) as implemented in scikit-learn:
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html
We include the following ad hoc rules:
- If authors are predicted which were not seen during training,
  these predictions will count as false predictions ('<UNK>' class)
  and they will negatively effect performance.
- If texts are left unattributed they will assigned to the ('<UNK>'
  class) and they will negatively effect performance.
- The <UNK> class is excluded from the macro-average across classes.
- If multiple test attributions are given for a single unknown document,
  only the first one will be taken into consideration.

Dependencies:
- Python 2.7 or 3.6 (we recommend the Anaconda Python distribution)
- scikit-learn

Usage from the command line:
>>> python pan19-cdaa-evaluator.py -i COLLECTION -a ANSWERS -o OUTPUT
where
    COLLECTION is the path to the main folder of the evaluation collection
    ANSWERS is the path to the answers folder of a submitted method
    OUTPUT is the path to the folder where the results of the evaluation will be saved

Example: 
>>>  python pan19-cdaa-evaluator.py -i ".\pan19-cross-domain-authorship-attribution-training-dataset-2019-01-23\" -a ".\answ
ers-unigram" -o ".\eval-unigram\"

# References:
@article{scikit-learn,
 title={Scikit-learn: Machine Learning in {P}ython},
 author={Pedregosa, F. and Varoquaux, G. and Gramfort, A. and Michel, V.
         and Thirion, B. and Grisel, O. and Blondel, M. and Prettenhofer, P.
         and Weiss, R. and Dubourg, V. and Vanderplas, J. and Passos, A. and
         Cournapeau, D. and Brucher, M. and Perrot, M. and Duchesnay, E.},
 journal={Journal of Machine Learning Research},
 volume={12},
 pages={2825--2830},
 year={2011}
}
"""

import argparse
import os
import json
import warnings
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np

def eval_measures(gt, pred):
    """Compute macro-averaged F1-scores, macro-averaged precision, 
    macro-averaged recall, and micro-averaged accuracy according the ad hoc
    rules discussed at the top of this file.
    Parameters
    ----------
    gt : dict
        Ground truth, where keys indicate text file names
        (e.g. `unknown00002.txt`), and values represent
        author labels (e.g. `candidate00003`)
    pred : dict
        Predicted attribution, where keys indicate text file names
        (e.g. `unknown00002.txt`), and values represent
        author labels (e.g. `candidate00003`)
    Returns
    -------
    f1 : float
        Macro-averaged F1-score
    precision : float
        Macro-averaged precision
    recall : float
        Macro-averaged recall
    accuracy : float
        Micro-averaged F1-score
    """

    actual_authors = list(gt.values())
    encoder = LabelEncoder().fit(['<UNK>'] + actual_authors)

    text_ids, gold_authors, silver_authors = [], [], []
    for text_id in sorted(gt):
        text_ids.append(text_id)
        gold_authors.append(gt[text_id])
        try:
            silver_authors.append(pred[text_id])
        except KeyError:
            # missing attributions get <UNK>:
            silver_authors.append('<UNK>')

    assert len(text_ids) == len(gold_authors)
    assert len(text_ids) == len(silver_authors)

    # replace non-existent silver authors with '<UNK>':
    silver_authors = [a if a in encoder.classes_ else '<UNK>' 
                      for a in silver_authors]

    gold_author_ints = encoder.transform(gold_authors)
    silver_author_ints = encoder.transform(silver_authors)

    # get F1 for individual classes (and suppress warnings):
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        labels=list(set(gold_author_ints))
        # Exclude the <UNK> class
        for x in labels:
            if encoder.inverse_transform(np.array([x]))=='<UNK>':
                labels.remove(x)
        f1 = f1_score(gold_author_ints,
                  silver_author_ints,
                  labels,
                  average='macro')
        precision = precision_score(gold_author_ints,
                  silver_author_ints,
                  labels,
                  average='macro')
        recall = recall_score(gold_author_ints,
                  silver_author_ints,
                  labels,
                  average='macro')
        accuracy = accuracy_score(gold_author_ints,
                  silver_author_ints)

    return f1,precision,recall

def evaluate(ground_truth_file,predictions_file):
    # Calculates evaluation measures for a single attribution problem
    gt = {}
    with open(ground_truth_file, 'r') as f:
        for attrib in json.load(f)['ground_truth']:
            gt[attrib['unknown-text']] = attrib['true-author']

    pred = {}
    with open(predictions_file, 'r') as f:
        for attrib in json.load(f):
            if attrib['unknown-text'] not in pred:
                pred[attrib['unknown-text']] = attrib['predicted-author']
    f1,precision,recall =  eval_measures(gt,pred)
    return round(f1,3), round(precision,3), round(recall,3)

def evaluate_all(path_collection,path_answers,path_out):
    # Calculates evaluation measures for a PAN-18 collection of attribution problems
    infocollection = path_collection+os.sep+'collection-info.json'
    problems = []
    data = []
    with open(infocollection, 'r') as f:
        for attrib in json.load(f):
            problems.append(attrib['problem-name'])
    scores=[];
    for problem in problems:
        f1,precision,recall=evaluate(path_collection+os.sep+problem+os.sep+'ground-truth.json',path_answers+os.sep+'answers-'+problem+'.json')
        scores.append(f1)
        data.append({'problem-name': problem, 'macro-f1': round(f1,3), 'macro-precision': round(precision,3), 'macro-recall': round(recall,3)})
        print(str(problem),'Macro-F1:',round(f1,3))
    overall_score=sum(scores)/len(scores)
    # Saving data to output files (out.json and evaluation.prototext)
    with open(path_out+os.sep+'out.json', 'w') as f:
        json.dump({'problems': data, 'overall_score': round(overall_score,3)}, f, indent=4, sort_keys=True)
    print('Overall score:', round(overall_score,3))
    prototext='measure {\n key: "mean macro-f1"\n value: "'+str(round(overall_score,3))+'"\n}\n'
    with open(path_out+os.sep+'evaluation.prototext', 'w') as f:
        f.write(prototext)
   
evaluate_all(base_dir,out_dir,eval_dir)

problem00001 Macro-F1: 0.62
problem00002 Macro-F1: 0.671
Overall score: 0.646


In [42]:
train_sents

['graceful ones.\n\n"One more," Marvelous said, sounding royally bored from his seat.\n\n"She’s tired," Joe said, though not unkindly. (the fucking jerk).\n\nHe was right; her muscles have long since turned to cotton with exhaustion and her knees refused to support her upright. But damned if she was going to take Joe’s offered hand to help her up, and damned if she was going to make herself look like a weakling in front of Marvelous, who - whether she liked it or not - was the fucking captain.\n\nLuka was determined to prove her worth to both of them, no matter what it took.\n\nSo she slapped Joe’s hand away and pushed herself off the fucking floor, and aimed the sword at his neck, willing her arm not to betray her.\n\n"Three more," she said, voice trembling, and Joe responded with a smirk.\n\nMarvelous yawned.\n\n(fucking jerks, both of them.)\n\n-\n\nA few weeks into their training, and Luka realized Joe was just that good in using his sword.\n\n"You have to learn how to read your op

### Exercise 5: Combine all features for each sentence.

Combine all the previous features, and generate a matrix encoding all previously mentioned features: unigrams, bigrams, trigrams and pos_tags. The resulting matrix should have the following dimensions: 3x31

You could use the `sklearn.pipeline.FeatureUnion` class.

In [ ]:
#toks = sentence_tokenize(train_sentences)

pipe2 = Pipeline (FeatureUnion([("uni", CountVectorizer(ngram_range = (1,3), min_df = 1)),("PoS", nltk.word_tokenize(train_sentences_1[0]))])


#CountVectorizer(ngram_range = (1,1), min_df = 1) #token_pattern=u"(?u)\\b\\w+\\b"

#bigrams_bow = bigr.fit_transform(train_sentences)
#union.fit_transform(train_sentences)    


### Extra to play with: Check this website and think about it. Do you think you can use this for something? (in the exam)

http://nadbordrozd.github.io/blog/2016/05/20/text-classification-with-word2vec/

## SHARE YOUR KNOWLEDGE!

### Do you know any other way of representing the features of the training/testing set?

Please share your knowledge using the forum from Absalon!!!